name: リクエスト
description: 実装要望
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: リクエストについての説明
      description: リクエストについての説明を明確かつ簡潔に記述してください。
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: 追加情報
      description: 必要に応じて、追加情報を書いてください。
    validations:
      required: false
